spring:
  application:
    name: spring-cloud-eureka-cli
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
